stages:
- name: Build
  steps:
  - runScriptConfig:
      image: alpine:latest
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: glodon-common/dingding:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.cn-beijing.aliyuncs.com
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./webhook-dingding.yaml
timeout: 60
branch:
  include:
  - dingding
